<?php
/**
 * My Application bootstrap file.
 */
use Nette\Application\Routers\Route;
use Nette\Diagnostics\Debugger;
 


// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->setDebugMode(true);
$configurator->enableDebugger(Debugger::DEVELOPMENT, __DIR__ . '/../log');


// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();

// Setup router
$container->router[] = new Route('index.php', 'Persons:list', Route::ONE_WAY);
$container->router[] = new Route('<presenter>/<action>[/<id>]', 'Persons:list');

// Configure and run the application!

$container->application->run();
